### PR TITLE
Remove Bootstrap 4 & Install Bootstrap 3

### PR DESCRIPTION
**Pull request by sreeramgoalla**
# **Home Page**
screen shot 2017-04-23 at 2 07 10 pm

# **Home Page (Mobile Version)**
screen shot 2017-04-23 at 2 07 03 pm

# **Login Page**
screen shot 2017-04-23 at 2 07 22 pm

# **Registration Page:**
screen shot 2017-04-23 at 2 07 32 pm

### CODE REVIEW

**Comment by nethulap** [comment]
Hey Sreeram, Any reason for moving from Bootstrap 4 to 3?

**Comment by sreeramgoalla** [comment]
Yea, I observed few styles/classes are not working Anna. Not sure, if it's because of any compatibly issues with my ruby or rails versions or if I'm using some incorrect bootstrap classes. So I kinda reverted it back.

**Comment by nethulap** [comment]
is it working now after reverting to version 3?

**Comment by sreeramgoalla** [comment]
Yea it's working now Anna. Specially while dealing with the Navigation bar classes here in this file ```app/views/layouts/application.html.haml```. For now I reverted it back to BS v3 instead of wasting my time figuring it out. But yeah we'll probably sit down one day and checkout the new BS v4 Gem.

**Comment by nethulap** [comment]
no worries.. 😄

**Pull request merged**
